package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"

	"encoding/json"
	"io/ioutil"
	"log"
	"time"
)

type Model struct {
	ID        uint       `gorm:"primary_key" json:"id"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `sql:"index" json:"deletedAt,omitempty"`
}
type User struct {
	Model
	Email string `validator:"email" gorm:"unique_index" json:"email"`
}
type Category struct {
	Model
	Name string `json:"name"`
}

type Topic struct {
	Model
	CategoryID uint
	Category   Category
	Title      string `json:"title"`
	Acl        []User `json:"acl" gorm:"many2many:topic_acl"`
}

func main() {
	Db, err := gorm.Open(
		"mysql",
		"root:123@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=True",
	)

	if err == nil {
		defer Db.Close()
		Db.LogMode(true)

		Db.AutoMigrate(&User{})
		Db.AutoMigrate(&Category{})
		Db.AutoMigrate(&Topic{})
		content, err := ioutil.ReadFile("test.json")

		var topic Topic

		err = json.Unmarshal(content, &topic)
		if err != nil {
			log.Fatal(err)
		}

		err = Db.Save(&topic).Error

		/*

			This is what happens now:

			UPDATE `categories` SET `created_at` = '2017-11-24 07:14:34', `updated_at` = '2018-01-18 00:12:18', `deleted_at` = NULL, `name` = 'Software'  WHERE `categories`.`deleted_at` IS NULL AND `categories`.`id` = '2'
			INSERT INTO `topics` (`created_at`,`updated_at`,`deleted_at`,`category_id`,`title`) VALUES ('2018-01-18 00:12:18','2018-01-18 00:12:18',NULL,'2','Omit users')
			UPDATE `users` SET `created_at` = '0001-01-01 00:00:00', `updated_at` = '2018-01-18 00:12:18', `deleted_at` = NULL, `email` = 'abc@gmail.com'  WHERE `users`.`deleted_at` IS NULL AND `users`.`id` = '18'
				(<autogenerated>:1)
			INSERT INTO `topic_acl` (`user_id`,`topic_id`) SELECT '18','3' FROM DUAL WHERE NOT EXISTS (SELECT * FROM `topic_acl` WHERE `user_id` = '18' AND `topic_id` = '3')
			UPDATE `users` SET `created_at` = '2017-11-24 16:15:32', `updated_at` = '2018-01-18 00:12:18', `deleted_at` = NULL, `email` = 'aas@ddd.com'  WHERE `users`.`deleted_at` IS NULL AND `users`.`id` = '16'
				(<autogenerated>:1)
			INSERT INTO `topic_acl` (`topic_id`,`user_id`) SELECT '3','16' FROM DUAL WHERE NOT EXISTS (SELECT * FROM `topic_acl` WHERE `topic_id` = '3' AND `user_id` = '16')


			But I'm looking into way to save topic and its references:

			INSERT INTO `topics` (`created_at`,`updated_at`,`deleted_at`,`category_id`,`title`) VALUES ('2018-01-18 00:12:18','2018-01-18 00:12:18',NULL,'2','Omit users')
				(<autogenerated>:1)
			INSERT INTO `topic_acl` (`user_id`,`topic_id`) SELECT '18','3' FROM DUAL WHERE NOT EXISTS (SELECT * FROM `topic_acl` WHERE `user_id` = '18' AND `topic_id` = '3')
				(<autogenerated>:1)
			INSERT INTO `topic_acl` (`topic_id`,`user_id`) SELECT '3','16' FROM DUAL WHERE NOT EXISTS (SELECT * FROM `topic_acl` WHERE `topic_id` = '3' AND `user_id` = '16')

		*/

	}

}
